[tool.uv.workspace]
members = [
    "tierkreis",
    "tierkreis_core",
    "tierkreis_visualization",
    "tierkreis_workers/*worker",
]


[dependency-groups]
# Default dev dependency group
dev = [
    { include-group = "lint" },
    { include-group = "test" },
    { include-group = "docs" },
    { include-group = "examples"}
]
lint = [
    "isort>=6.0.1",
    "ruff>=0.12.5",
    "pyright>=1.1.400",
]
test = [
    "pytest>=6.2,<9",
    "pytest-asyncio>=0.16,<0.17",
    "pytest-cov>=5.0,<6",
    "pydantic>=2.9.2",
]
docs = [
    "sphinx>=8.2",
    "myst-parser>=4.0.1",
    "sphinx-autodoc2>=0.5.0",
    "myst-nb>=1.3.0",
    "furo>=2025.7.19",
]
examples = ["pyscf>=2.9.0"]

[tool.uv.sources]
tierkreis_core = { workspace = true }
quantinuum-sphinx = { git = "https://github.com/CQCL/quantinuum-sphinx.git" }

[tool.maturin]
module-name = "tierkreis_core._tierkreis_core"
python-source = "tierkreis_core/python/"
manifest-path = "tierkreis_core/Cargo.toml"
features = ["pyo3/extension-module"]
